from __future__ import annotations

import html
import json
import os
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = Path(os.getenv("TRUTH_ARTIFACT_DIR", ROOT / "artifacts"))
TZ = ZoneInfo("Europe/Athens")
SERVICES = ("facebook", "instagram", "tiktok")


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"ok": False, "status": "parse_error", "error": f"Unable to parse {path}"}


def esc(value: Any) -> str:
    return html.escape(str(value if value is not None else ""))


def main() -> int:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    result = load_json(ARTIFACT_DIR / "scheduler-result.json")
    completed = result.get("ok") is True and result.get("status") == "completed"

    raw_queue_slo = result.get("queue_slo")
    raw_channel_slo = result.get("channel_queue_slo")
    queue_known = isinstance(raw_queue_slo, dict) and isinstance(raw_channel_slo, dict) and bool(raw_channel_slo)
    queue_slo = raw_queue_slo if queue_known else None
    channel_slo = raw_channel_slo if queue_known else {}

    actions = list(result.get("actions") or [])
    action_counts = dict(Counter(str(a.get("type") or "unknown") for a in actions))
    blocked = int(action_counts.get("blocked") or 0)
    underfilled = [service for service in SERVICES if queue_known and not (channel_slo.get(service) or {}).get("met")]
    execution_error = str(result.get("error") or "").strip()

    if not completed:
        incident = str(result.get("status") or "scheduler_execution_missing_or_failed")
        if execution_error:
            incident = f"{incident}: {execution_error}"
    elif underfilled:
        incident = "queue_underfilled:" + ",".join(underfilled)
    elif blocked:
        incident = f"blocked_jobs:{blocked}"
    else:
        incident = "none"

    overall = "HEALTHY" if completed and queue_known and not underfilled and incident == "none" else "CRITICAL"
    generated_at = datetime.now(TZ).isoformat(timespec="seconds")
    truth_source = result.get("full_truth_source") if queue_known else "buffer_unreadable_current_state_unknown"

    dashboard = {
        "generated_at": generated_at,
        "overall_status": overall,
        "scheduler_completed": completed,
        "incident": incident,
        "execution_error": execution_error or None,
        "queue_truth_status": "verified" if queue_known else "unknown",
        "queue_slo": queue_slo,
        "channel_queue_slo": channel_slo,
        "full_truth_source": truth_source,
        "weekly_target": result.get("weekly_target"),
        "scheduled_this_run": result.get("scheduled_this_run", 0),
        "preclaim_capacity": result.get("preclaim_capacity") or {},
        "refill": result.get("refill") or {},
        "outbox": {
            "jobs_received": result.get("outbox_jobs_received", 0),
            "jobs_received_by_platform": result.get("outbox_jobs_received_by_platform") or {},
            "pending_preview_count": result.get("outbox_pending_preview_count"),
            "pending_by_platform": result.get("outbox_pending_by_platform") or {},
            "sync": result.get("outbox_sync") or {},
        },
        "action_counts": action_counts,
        "next_scheduled": result.get("next_scheduled") or [],
        "truth_notes": [
            "GREEN requires a verified current Buffer snapshot plus 10/10 on every connected channel after confirmed createPost acknowledgements.",
            "If Buffer cannot be read, queue state is UNKNOWN. UNKNOWN never means 0/30 or empty.",
            "The scheduler uses one Buffer runtime snapshot per hourly run; accepted createPost responses complete post-write truth without a second Buffer read.",
            "No filler content is generated by SocialScheduler. Underfill stays CRITICAL until SocialMarket supplies valid approved content.",
        ],
    }
    (ARTIFACT_DIR / "full-truth.json").write_text(json.dumps(dashboard, ensure_ascii=False, indent=2), encoding="utf-8")

    icon = "✅" if overall == "HEALTHY" else "🚨"
    md = f"""# {icon} SocialScheduler Admin Dashboard

**Updated:** {generated_at}  
**Overall:** **{overall}**  
**Scheduler completed:** **{completed}**  
**Queue truth:** **{'VERIFIED' if queue_known else 'UNKNOWN'}**  
**Truth source:** `{truth_source}`

## Buffer Queue

| Channel | Queue | Fill | Missing | Status |
|---|---:|---:|---:|---|
"""
    for service in SERVICES:
        row = channel_slo.get(service) if queue_known else None
        if row:
            md += f"| {service.title()} | **{row.get('active', 0)}/{row.get('limit', 10)}** | **{float(row.get('fill_rate_pct', 0)):.2f}%** | {row.get('missing', 0)} | {'✅' if row.get('met') else '🚨'} |\n"
        else:
            md += f"| {service.title()} | **UNKNOWN** | **UNKNOWN** | UNKNOWN | ⚠️ UNREADABLE |\n"

    if queue_known and queue_slo:
        total_line = f"**TOTAL:** **{queue_slo.get('active', 0)}/{queue_slo.get('limit', 30)}** · Fill **{float(queue_slo.get('fill_rate_pct', 0)):.2f}%** · Missing **{queue_slo.get('missing', 0)}**"
    else:
        total_line = "**TOTAL:** **UNKNOWN** — Buffer could not be read. This is not evidence of an empty queue."

    md += f"""
{total_line}

## SocialMarket / Outbox

| KPI | Value |
|---|---|
| Claimed this run | **{result.get('outbox_jobs_received', 0)}** |
| Claimed by platform | `{json.dumps(result.get('outbox_jobs_received_by_platform') or {}, ensure_ascii=False)}` |
| Pending approved preview | **{result.get('outbox_pending_preview_count', 'unknown')}** |
| Pending by platform | `{json.dumps(result.get('outbox_pending_by_platform') or {}, ensure_ascii=False)}` |
| Rolling refill | `{json.dumps(result.get('refill') or {}, ensure_ascii=False)}` |
| Scheduled this run | **{result.get('scheduled_this_run', 0)}** |
| Weekly target | **{result.get('weekly_target', 'unknown')}** |

## System Truth

**Incident:** `{incident}`  
**Execution error:** `{execution_error or 'none'}`  
**Scheduler actions:** `{json.dumps(action_counts, ensure_ascii=False)}`

- GREEN only when the current Buffer state is readable and Facebook, Instagram and TikTok are each **10/10**.
- **UNKNOWN is never rendered as 0/30.**
- Workflow success alone is not health.
- SocialScheduler never invents filler content to fake a full queue.

## Next scheduled posts

| Due | Channel | Source | Post ID |
|---|---|---|---|
"""
    for row in dashboard["next_scheduled"][:30]:
        md += f"| {row.get('dueAt') or ''} | {row.get('service') or ''} | {row.get('source') or ''} | {row.get('id') or ''} |\n"
    if not dashboard["next_scheduled"]:
        md += "| — | — | — | — |\n"
    (ARTIFACT_DIR / "admin-dashboard.md").write_text(md, encoding="utf-8")

    html_rows = []
    for service in SERVICES:
        row = channel_slo.get(service) if queue_known else None
        if row:
            status = "OK" if row.get("met") else "CRITICAL"
            html_rows.append(
                f"<tr><td>{esc(service.title())}</td><td>{esc(row.get('active', 0))}/{esc(row.get('limit', 10))}</td>"
                f"<td>{esc(row.get('fill_rate_pct', 0))}%</td><td>{status}</td></tr>"
            )
        else:
            html_rows.append(f"<tr><td>{esc(service.title())}</td><td>UNKNOWN</td><td>UNKNOWN</td><td>UNREADABLE</td></tr>")
    rows = "".join(html_rows)

    page = f"""<!doctype html><html><head><meta charset='utf-8'><title>SocialScheduler Admin</title>
<style>body{{font-family:system-ui;margin:36px;max-width:980px}}.ok{{color:#067647}}.bad{{color:#b42318}}table{{border-collapse:collapse;width:100%}}td,th{{border-bottom:1px solid #ddd;padding:10px;text-align:left}}</style></head><body>
<h1>SocialScheduler Admin Dashboard</h1><h2 class='{'ok' if overall == 'HEALTHY' else 'bad'}'>{icon} {esc(overall)}</h2><p>Updated {esc(generated_at)}</p>
<p><strong>Queue truth:</strong> {'VERIFIED' if queue_known else 'UNKNOWN — Buffer unreadable; not zero.'}</p>
<table><thead><tr><th>Channel</th><th>Queue</th><th>Fill</th><th>Status</th></tr></thead><tbody>{rows}</tbody></table>
<h3>Incident</h3><p><strong>{esc(incident)}</strong></p><h3>Full Truth JSON</h3><pre>{esc(json.dumps(dashboard, ensure_ascii=False, indent=2))}</pre></body></html>"""
    (ARTIFACT_DIR / "admin-dashboard.html").write_text(page, encoding="utf-8")

    print(json.dumps(dashboard, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
